"use client";

// import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AppContextProvider } from "@/context/AppContext";

const urbanist = Urbanist({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={`${urbanist.className} antialiased min-w-[320px]`}>
          <div className="w-full flex flex-col items-center">
            <Header />
            <main className="flex flex-col px-4 sm:px-6 max-w-[1200px] w-full">{children}</main>
            <Footer />
          </div>
        </body>
      </AppContextProvider>
    </html>
  );
}
